// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNm5JY5Dkx-M_c-XZcUTtpSudwfLMQGLM',
    appId: '1:1044665638768:web:e9d0da8c6d3ccaeb5a39b5',
    messagingSenderId: '1044665638768',
    projectId: 'barberxe-fcfe3',
    authDomain: 'barberxe-fcfe3.firebaseapp.com',
    storageBucket: 'barberxe-fcfe3.firebasestorage.app',
    measurementId: 'G-LG6N477CRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDguWtJad8BPVwizBjcXS69sPYtnvi9Sfw',
    appId: '1:1044665638768:android:d626d475b37785075a39b5',
    messagingSenderId: '1044665638768',
    projectId: 'barberxe-fcfe3',
    storageBucket: 'barberxe-fcfe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF1TeNiyln1O09jDbOZjku_O_PMkB91hc',
    appId: '1:1044665638768:ios:e878d5cfc1a965ba5a39b5',
    messagingSenderId: '1044665638768',
    projectId: 'barberxe-fcfe3',
    storageBucket: 'barberxe-fcfe3.firebasestorage.app',
    iosBundleId: 'com.example.barberXe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF1TeNiyln1O09jDbOZjku_O_PMkB91hc',
    appId: '1:1044665638768:ios:e878d5cfc1a965ba5a39b5',
    messagingSenderId: '1044665638768',
    projectId: 'barberxe-fcfe3',
    storageBucket: 'barberxe-fcfe3.firebasestorage.app',
    iosBundleId: 'com.example.barberXe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNm5JY5Dkx-M_c-XZcUTtpSudwfLMQGLM',
    appId: '1:1044665638768:web:b226502fd71d36ca5a39b5',
    messagingSenderId: '1044665638768',
    projectId: 'barberxe-fcfe3',
    authDomain: 'barberxe-fcfe3.firebaseapp.com',
    storageBucket: 'barberxe-fcfe3.firebasestorage.app',
    measurementId: 'G-XN349XY986',
  );
}
